---
- name: Configure Tower in environment {{ __tower_env }}
  hosts: tower_{{ __tower_env }}
  connection: local
  gather_facts: no


  collections:
    - ansible.tower


  vars:
    __tower_env     : "{{ tower_env | default('blue') }}"
    tower_hostname  : "{{ ansible_host }}"
    tower_templates : "{{ tower_templates_global +
                          tower_templates_blue   | default([]) +
                          tower_templates_green  | default([]) +
                          tower_templates_purple | default([]) }}"
    tower_projects  : "{{ tower_projects_global +
                          tower_projects_blue   | default([]) +
                          tower_projects_green  | default([]) +
                          tower_projects_purple | default([]) }}"


  tasks:
    - include_role:
        name: redhat_cop.tower_configuration.organizations

    - include_role:
        name: redhat_cop.tower_configuration.projects

    - include_role:
        name: redhat_cop.tower_configuration.inventories

    - include_role:
        name: redhat_cop.tower_configuration.inventory_sources

    - include_role:
        name: redhat_cop.tower_configuration.inventory_source_update

    - include_role:
        name: redhat_cop.tower_configuration.hosts

    - include_role:
        name: redhat_cop.tower_configuration.credentials

    - include_role:
        name: redhat_cop.tower_configuration.job_templates


...
