---
tower_inventories:
  - name: Lab Inventory
    organization: Red Hat Consulting

  - name: BlueGreenTower
    organization: Red Hat Consulting
    variables:
      ansible_connection: local

  - name: HAProxy-BlueGreenTower
    organization: Red Hat Consulting

  - name: container_inventory
    organization: Red Hat Consulting

  - name: placeholder
    organization: Red Hat Consulting


tower_inventory_sources:
  - name: bluegreensrc
    organization: Red Hat Consulting
    inventory: BlueGreenTower
    source: scm
    source_project: BlueGreenTower
    source_path: inventory
    overwrite: yes
    overwrite_vars: yes

  - name: haproxysrc
    organization: Red Hat Consulting
    inventory: HAProxy-BlueGreenTower
    source: scm
    source_project: HAProxy-BlueGreenTower
    source_path: inventory/hosts
    overwrite: yes
    overwrite_vars: yes

  - name: labinvsrc
    organization: Red Hat Consulting
    inventory: Lab Inventory
    source: scm
    source_project: Tower Tests
    source_path: inventory/hosts
    overwrite: yes
    overwrite_vars: yes


...
