---
tower_templates_global:
  - name           : BlueGreenDeploy (Blue)
    organization   : Red Hat Consulting
    project        : BlueGreenTower
    playbook       : configure_tower.yml
    inventory      : BlueGreenTower
    credentials    : BlueGreenTower
    extra_vars     :
      tower_env    : blue

  - name           : BlueGreenDeploy (Green)
    organization   : Red Hat Consulting
    project        : BlueGreenTower
    playbook       : configure_tower.yml
    inventory      : BlueGreenTower
    credentials    : BlueGreenTower
    extra_vars     :
      tower_env    : green

  - name           : BlueGreenDeploy (Purple)
    organization   : Red Hat Consulting
    project        : BlueGreenTower
    playbook       : configure_tower.yml
    inventory      : BlueGreenTower
    credentials    : BlueGreenTower
    extra_vars     :
      tower_env    : purple

  - name           : HAProxy-BlueGreenTower
    organization   : Red Hat Consulting
    project        : HAProxy-BlueGreenTower
    playbook       : haproxy.yml
    inventory      : HAProxy-BlueGreenTower
    credentials    : lab-machine-cred
    extra_vars     :
      __haproxy_use_backend: aap_blue


...
