---
tower_hosts:
  - name: lab-prod-1
    inventory: Lab Inventory

  - name: lab-prod-2
    inventory: Lab Inventory

  - name: api-host
    variables:
      ansible_connection: local
    inventory: API Inventory


...
