---
tower_templates_green:
  - name           : Debug Playbook (Green)
    organization   : Red Hat Consulting
    project        : Tower Tests
    playbook       : debug.yml
    inventory      : Lab Inventory
    credentials    : lab-machine-cred
    survey_enabled : yes
    survey:
      name        : ""
      description : ""
      spec:
        - question_name : Debug message
          required      : yes
          type          : text
          variable      : __message
          min           : 0
          max           : 1024
          default       : Hello from Green


  - name                    : FileCreationSingleTest
    organization            : Red Hat Consulting
    project                 : Tower Tests
    playbook                : file-creation-single.yml
    inventory               : Lab Inventory
    credentials             : lab-machine-cred
    allow_simultaneous      : yes
    ask_variables_on_launch : yes


  - name               : FileExistenceTest
    organization       : Red Hat Consulting
    project            : Tower Tests
    playbook           : file-existence-test.yml
    inventory          : Lab Inventory
    credentials        : lab-machine-cred


...
